/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OmiSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  memoriesFolder: "Omi/Memories",
  conversationsFolder: "Omi/Conversations",
  actionItemsFolder: "Omi/Action Items",
  autoSync: false,
  syncIntervalMinutes: 30,
  lastSyncTimestamp: 0,
  syncOnStartup: true,
  includeTranscript: true,
  memoryTags: "omi, omi/memory",
  conversationTags: "omi, omi/conversation",
  actionItemTags: "omi, omi/action-item",
  actionItemCompletedTags: "completed, done",
  actionItemPendingTags: "todo, pending",
  includeCategoryTag: true
};
var OmiSyncPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.syncInterval = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("refresh-cw", "Sync Omi Data", async () => {
      await this.syncAll();
    });
    this.addCommand({
      id: "sync-all-omi",
      name: "Sync all Omi data",
      callback: async () => {
        await this.syncAll();
      }
    });
    this.addCommand({
      id: "sync-omi-memories",
      name: "Sync Omi memories only",
      callback: async () => {
        await this.syncMemories();
      }
    });
    this.addCommand({
      id: "sync-omi-conversations",
      name: "Sync Omi conversations only",
      callback: async () => {
        await this.syncConversations();
      }
    });
    this.addCommand({
      id: "sync-omi-action-items",
      name: "Sync Omi action items only",
      callback: async () => {
        await this.syncActionItems();
      }
    });
    this.addSettingTab(new OmiSyncSettingTab(this.app, this));
    if (this.settings.autoSync) {
      this.startAutoSync();
    }
    if (this.settings.syncOnStartup && this.settings.apiKey) {
      setTimeout(async () => {
        new import_obsidian.Notice("Omi Sync: Starting initial sync...");
        await this.syncAll();
      }, 3e3);
    }
  }
  onunload() {
    this.stopAutoSync();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ============================================================================
  // Auto-Sync Management
  // ============================================================================
  startAutoSync() {
    this.stopAutoSync();
    const intervalMs = this.settings.syncIntervalMinutes * 60 * 1e3;
    this.syncInterval = window.setInterval(async () => {
      console.log("Omi Sync: Auto-sync triggered");
      await this.syncAll(true);
    }, intervalMs);
    this.registerInterval(this.syncInterval);
  }
  stopAutoSync() {
    if (this.syncInterval !== null) {
      window.clearInterval(this.syncInterval);
      this.syncInterval = null;
    }
  }
  // ============================================================================
  // API Communication
  // ============================================================================
  async apiRequest(endpoint, params) {
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("Omi Sync: Please configure your API key in settings");
      return null;
    }
    const baseUrl = "https://api.omi.me/v1/dev";
    let url = `${baseUrl}${endpoint}`;
    if (params) {
      const searchParams = new URLSearchParams(params);
      url += `?${searchParams.toString()}`;
    }
    const requestParams = {
      url,
      method: "GET",
      headers: {
        Authorization: `Bearer ${this.settings.apiKey}`,
        "Content-Type": "application/json"
      }
    };
    try {
      const response = await (0, import_obsidian.requestUrl)(requestParams);
      return response.json;
    } catch (error) {
      console.error(`Omi Sync API Error (${endpoint}):`, error);
      throw error;
    }
  }
  async fetchMemories(limit = 100, offset = 0) {
    const memories = await this.apiRequest("/user/memories", {
      limit: limit.toString(),
      offset: offset.toString()
    });
    return memories || [];
  }
  async fetchConversations(limit = 100, offset = 0) {
    const conversations = await this.apiRequest("/user/conversations", {
      limit: limit.toString(),
      offset: offset.toString(),
      include_transcript: "true"
    });
    return conversations || [];
  }
  async fetchActionItems(limit = 100, offset = 0) {
    const actionItems = await this.apiRequest("/user/action-items", {
      limit: limit.toString(),
      offset: offset.toString()
    });
    return actionItems || [];
  }
  // ============================================================================
  // Folder Management
  // ============================================================================
  async ensureFolderExists(folderPath) {
    const normalizedPath = (0, import_obsidian.normalizePath)(folderPath);
    const folder = this.app.vault.getAbstractFileByPath(normalizedPath);
    if (!folder) {
      await this.app.vault.createFolder(normalizedPath);
    }
  }
  // ============================================================================
  // Content Generation
  // ============================================================================
  parseTags(tagString) {
    if (!tagString || tagString.trim() === "") {
      return [];
    }
    return tagString.split(",").map((tag) => tag.trim()).filter((tag) => tag.length > 0);
  }
  generateMemoryContent(memory) {
    const frontmatter = {
      id: memory.id,
      type: "omi-memory",
      synced: (/* @__PURE__ */ new Date()).toISOString()
    };
    if (memory.created_at)
      frontmatter.created = memory.created_at;
    if (memory.updated_at)
      frontmatter.updated = memory.updated_at;
    if (memory.category)
      frontmatter.category = memory.category;
    if (memory.visibility)
      frontmatter.visibility = memory.visibility;
    const tags = this.parseTags(this.settings.memoryTags);
    if (this.settings.includeCategoryTag && memory.category) {
      const categoryTag = memory.category.toLowerCase().replace(/\s+/g, "-");
      if (!tags.includes(categoryTag)) {
        tags.push(categoryTag);
      }
    }
    if (memory.tags && memory.tags.length > 0) {
      for (const tag of memory.tags) {
        if (!tags.includes(tag)) {
          tags.push(tag);
        }
      }
    }
    if (tags.length > 0) {
      frontmatter.tags = tags;
    }
    let content = this.generateFrontmatter(frontmatter);
    const contentLines = memory.content.split("\n");
    const firstLine = contentLines[0].substring(0, 60);
    const title = firstLine.length > 50 ? firstLine.substring(0, 50) + "..." : firstLine;
    const emoji = this.getCategoryEmoji(memory.category);
    content += `# ${emoji} ${title}

`;
    content += `## Memory

${memory.content}

`;
    if (memory.category) {
      content += `**Category:** ${memory.category}
`;
    }
    if (memory.manually_added) {
      content += `**Manually Added:** Yes
`;
    }
    content += "\n";
    content += `---
`;
    content += `*Synced from Omi on ${(/* @__PURE__ */ new Date()).toLocaleString()}*
`;
    return content;
  }
  getCategoryEmoji(category) {
    if (!category)
      return "\u{1F9E0}";
    const emojiMap = {
      "interesting": "\u{1F4A1}",
      "system": "\u2699\uFE0F",
      "manual": "\u{1F4DD}",
      "personal": "\u{1F464}",
      "work": "\u{1F4BC}",
      "business": "\u{1F4CA}",
      "health": "\u{1F3E5}",
      "finance": "\u{1F4B0}",
      "travel": "\u2708\uFE0F",
      "food": "\u{1F37D}\uFE0F",
      "entertainment": "\u{1F3AC}",
      "education": "\u{1F4DA}",
      "social": "\u{1F465}"
    };
    return emojiMap[category.toLowerCase()] || "\u{1F9E0}";
  }
  generateConversationContent(conversation) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const frontmatter = {
      id: conversation.id,
      type: "omi-conversation",
      created: conversation.created_at,
      source: conversation.source || "unknown",
      synced: (/* @__PURE__ */ new Date()).toISOString()
    };
    if (conversation.started_at)
      frontmatter.started = conversation.started_at;
    if (conversation.finished_at)
      frontmatter.finished = conversation.finished_at;
    if (conversation.language)
      frontmatter.language = conversation.language;
    if ((_a = conversation.structured) == null ? void 0 : _a.category)
      frontmatter.category = conversation.structured.category;
    const tags = this.parseTags(this.settings.conversationTags);
    if (this.settings.includeCategoryTag && ((_b = conversation.structured) == null ? void 0 : _b.category)) {
      const categoryTag = conversation.structured.category.toLowerCase().replace(/\s+/g, "-");
      if (!tags.includes(categoryTag)) {
        tags.push(categoryTag);
      }
    }
    if (tags.length > 0) {
      frontmatter.tags = tags;
    }
    let content = this.generateFrontmatter(frontmatter);
    const title = ((_c = conversation.structured) == null ? void 0 : _c.title) || this.generateConversationTitle(conversation);
    const emoji = ((_d = conversation.structured) == null ? void 0 : _d.emoji) || "\u{1F4AC}";
    content += `# ${emoji} ${title}

`;
    if (conversation.started_at && conversation.finished_at) {
      const start = new Date(conversation.started_at);
      const end = new Date(conversation.finished_at);
      const durationMs = end.getTime() - start.getTime();
      const durationMins = Math.round(durationMs / 6e4);
      content += `**Duration:** ${durationMins} minutes

`;
    }
    if ((_e = conversation.structured) == null ? void 0 : _e.overview) {
      content += `## Overview

${conversation.structured.overview}

`;
    }
    if (((_f = conversation.structured) == null ? void 0 : _f.action_items) && conversation.structured.action_items.length > 0) {
      content += `## Action Items

`;
      for (const item of conversation.structured.action_items) {
        const checkbox = item.completed ? "[x]" : "[ ]";
        content += `- ${checkbox} ${item.description}
`;
      }
      content += "\n";
    }
    if (((_g = conversation.structured) == null ? void 0 : _g.events) && conversation.structured.events.length > 0) {
      content += `## Events

`;
      for (const event of conversation.structured.events) {
        content += `### ${event.title}
`;
        if (event.description)
          content += `${event.description}
`;
        if (event.start)
          content += `- **Start:** ${event.start}
`;
        if (event.duration)
          content += `- **Duration:** ${event.duration} minutes
`;
        content += "\n";
      }
    }
    if (this.settings.includeTranscript) {
      if (conversation.transcript_segments && conversation.transcript_segments.length > 0) {
        content += `## Transcript

`;
        for (const segment of conversation.transcript_segments) {
          const speaker = segment.is_user ? "**You**" : segment.speaker || `Speaker ${(_h = segment.speaker_id) != null ? _h : ""}`;
          content += `> ${speaker}: ${segment.text}
>
`;
        }
        content += "\n";
      } else {
        content += `## Transcript

*No transcript available for this conversation.*

`;
      }
    }
    content += `---
`;
    content += `*Synced from Omi on ${(/* @__PURE__ */ new Date()).toLocaleString()}*
`;
    return content;
  }
  generateConversationTitle(conversation) {
    const date = new Date(conversation.created_at);
    return `Conversation - ${date.toLocaleDateString()} ${date.toLocaleTimeString()}`;
  }
  generateActionItemContent(actionItem) {
    const frontmatter = {
      id: actionItem.id,
      type: "omi-action-item",
      created: actionItem.created_at,
      completed: actionItem.completed || false,
      source: actionItem.source || "unknown",
      synced: (/* @__PURE__ */ new Date()).toISOString()
    };
    if (actionItem.completed_at)
      frontmatter.completed_at = actionItem.completed_at;
    if (actionItem.memory_id)
      frontmatter.memory_id = actionItem.memory_id;
    if (actionItem.conversation_id)
      frontmatter.conversation_id = actionItem.conversation_id;
    const tags = this.parseTags(this.settings.actionItemTags);
    if (actionItem.completed) {
      const completedTags = this.parseTags(this.settings.actionItemCompletedTags);
      tags.push(...completedTags.filter((t) => !tags.includes(t)));
    } else {
      const pendingTags = this.parseTags(this.settings.actionItemPendingTags);
      tags.push(...pendingTags.filter((t) => !tags.includes(t)));
    }
    if (tags.length > 0) {
      frontmatter.tags = tags;
    }
    let content = this.generateFrontmatter(frontmatter);
    const status = actionItem.completed ? "\u2705" : "\u2B1C";
    content += `# ${status} Action Item

`;
    const checkbox = actionItem.completed ? "[x]" : "[ ]";
    content += `- ${checkbox} ${actionItem.description}

`;
    content += `## Details

`;
    content += `- **Created:** ${new Date(actionItem.created_at).toLocaleString()}
`;
    if (actionItem.completed && actionItem.completed_at) {
      content += `- **Completed:** ${new Date(actionItem.completed_at).toLocaleString()}
`;
    }
    if (actionItem.memory_id) {
      const memoryFileName = this.sanitizeFileName(`memory-${actionItem.memory_id}`);
      content += `- **Related Memory:** [[${this.settings.memoriesFolder}/${memoryFileName}]]
`;
    }
    if (actionItem.conversation_id) {
      const convFileName = this.sanitizeFileName(`conversation-${actionItem.conversation_id}`);
      content += `- **Related Conversation:** [[${this.settings.conversationsFolder}/${convFileName}]]
`;
    }
    content += "\n";
    content += `---
`;
    content += `*Synced from Omi on ${(/* @__PURE__ */ new Date()).toLocaleString()}*
`;
    return content;
  }
  generateFrontmatter(data) {
    let frontmatter = "---\n";
    for (const [key, value] of Object.entries(data)) {
      if (Array.isArray(value)) {
        frontmatter += `${key}:
`;
        for (const item of value) {
          frontmatter += `  - ${item}
`;
        }
      } else if (typeof value === "object" && value !== null) {
        frontmatter += `${key}: ${JSON.stringify(value)}
`;
      } else {
        frontmatter += `${key}: ${value}
`;
      }
    }
    frontmatter += "---\n\n";
    return frontmatter;
  }
  sanitizeFileName(name) {
    return name.replace(/[\\/:*?"<>|]/g, "-").replace(/\s+/g, " ").trim().substring(0, 100);
  }
  generateFileName(item, type) {
    var _a;
    let dateStr = "";
    if (type === "memory") {
      const memory = item;
      const date = memory.created_at ? new Date(memory.created_at) : /* @__PURE__ */ new Date();
      dateStr = date.toISOString().split("T")[0];
    } else if (type === "conversation") {
      const conv = item;
      const date = new Date(conv.created_at);
      dateStr = date.toISOString().split("T")[0];
    } else {
      const action = item;
      const date = new Date(action.created_at);
      dateStr = date.toISOString().split("T")[0];
    }
    let title = "";
    if (type === "memory") {
      const memory = item;
      const firstLine = memory.content.split("\n")[0];
      title = firstLine.substring(0, 50);
    } else if (type === "conversation") {
      const conv = item;
      title = ((_a = conv.structured) == null ? void 0 : _a.title) || item.id.substring(0, 8);
    } else if (type === "action-item") {
      title = item.description.substring(0, 50);
    } else {
      title = item.id.substring(0, 8);
    }
    const sanitizedTitle = this.sanitizeFileName(title);
    return `${dateStr} - ${sanitizedTitle}`;
  }
  // ============================================================================
  // Sync Operations
  // ============================================================================
  async syncAll(silent = false) {
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("Omi Sync: Please configure your API key in settings");
      return { memories: 0, conversations: 0, actionItems: 0, errors: ["No API key configured"] };
    }
    if (!silent) {
      new import_obsidian.Notice("Omi Sync: Starting sync...");
    }
    const result = {
      memories: 0,
      conversations: 0,
      actionItems: 0,
      errors: []
    };
    try {
      const memoriesResult = await this.syncMemories(true);
      result.memories = memoriesResult;
      const conversationsResult = await this.syncConversations(true);
      result.conversations = conversationsResult;
      const actionItemsResult = await this.syncActionItems(true);
      result.actionItems = actionItemsResult;
      this.settings.lastSyncTimestamp = Date.now();
      await this.saveSettings();
      if (!silent) {
        new import_obsidian.Notice(
          `Omi Sync complete!
\u{1F4DD} ${result.memories} memories
\u{1F4AC} ${result.conversations} conversations
\u2705 ${result.actionItems} action items`
        );
      }
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      result.errors.push(errorMsg);
      new import_obsidian.Notice(`Omi Sync error: ${errorMsg}`);
    }
    return result;
  }
  async syncMemories(silent = false) {
    if (!this.settings.apiKey) {
      if (!silent)
        new import_obsidian.Notice("Omi Sync: Please configure your API key");
      return 0;
    }
    try {
      await this.ensureFolderExists(this.settings.memoriesFolder);
      const memories = await this.fetchMemories();
      let syncedCount = 0;
      for (const memory of memories) {
        if (!memory.content || memory.content.trim() === "")
          continue;
        const fileName = this.generateFileName(memory, "memory");
        const filePath = (0, import_obsidian.normalizePath)(`${this.settings.memoriesFolder}/${fileName}.md`);
        const existingFile = this.app.vault.getAbstractFileByPath(filePath);
        const content = this.generateMemoryContent(memory);
        if (existingFile) {
          await this.app.vault.modify(existingFile, content);
        } else {
          await this.app.vault.create(filePath, content);
        }
        syncedCount++;
      }
      if (!silent) {
        new import_obsidian.Notice(`Omi Sync: Synced ${syncedCount} memories`);
      }
      return syncedCount;
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice(`Omi Sync error (memories): ${errorMsg}`);
      console.error("Omi Sync memories error:", error);
      return 0;
    }
  }
  async syncConversations(silent = false) {
    if (!this.settings.apiKey) {
      if (!silent)
        new import_obsidian.Notice("Omi Sync: Please configure your API key");
      return 0;
    }
    try {
      await this.ensureFolderExists(this.settings.conversationsFolder);
      const conversations = await this.fetchConversations();
      let syncedCount = 0;
      for (const conversation of conversations) {
        const fileName = this.generateFileName(conversation, "conversation");
        const filePath = (0, import_obsidian.normalizePath)(`${this.settings.conversationsFolder}/${fileName}.md`);
        const existingFile = this.app.vault.getAbstractFileByPath(filePath);
        const content = this.generateConversationContent(conversation);
        if (existingFile) {
          await this.app.vault.modify(existingFile, content);
        } else {
          await this.app.vault.create(filePath, content);
        }
        syncedCount++;
      }
      if (!silent) {
        new import_obsidian.Notice(`Omi Sync: Synced ${syncedCount} conversations`);
      }
      return syncedCount;
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice(`Omi Sync error (conversations): ${errorMsg}`);
      console.error("Omi Sync conversations error:", error);
      return 0;
    }
  }
  async syncActionItems(silent = false) {
    if (!this.settings.apiKey) {
      if (!silent)
        new import_obsidian.Notice("Omi Sync: Please configure your API key");
      return 0;
    }
    try {
      await this.ensureFolderExists(this.settings.actionItemsFolder);
      const actionItems = await this.fetchActionItems();
      let syncedCount = 0;
      for (const actionItem of actionItems) {
        if (actionItem.deleted)
          continue;
        const fileName = this.generateFileName(actionItem, "action-item");
        const filePath = (0, import_obsidian.normalizePath)(`${this.settings.actionItemsFolder}/${fileName}.md`);
        const existingFile = this.app.vault.getAbstractFileByPath(filePath);
        const content = this.generateActionItemContent(actionItem);
        if (existingFile) {
          await this.app.vault.modify(existingFile, content);
        } else {
          await this.app.vault.create(filePath, content);
        }
        syncedCount++;
      }
      if (!silent) {
        new import_obsidian.Notice(`Omi Sync: Synced ${syncedCount} action items`);
      }
      return syncedCount;
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice(`Omi Sync error (action items): ${errorMsg}`);
      console.error("Omi Sync action items error:", error);
      return 0;
    }
  }
};
var OmiSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "Omi Sync Settings" });
    containerEl.createEl("h2", { text: "API Configuration" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc(
      "Your Omi Developer API key. Get it from Settings \u2192 Developer \u2192 Create Key in the Omi app."
    ).addText(
      (text) => text.setPlaceholder("omi_dev_your_key_here").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Test Connection").setDesc("Verify your API key is working correctly").addButton(
      (button) => button.setButtonText("Test").onClick(async () => {
        if (!this.plugin.settings.apiKey) {
          new import_obsidian.Notice("Please enter an API key first");
          return;
        }
        button.setButtonText("Testing...");
        button.setDisabled(true);
        try {
          const result = await this.plugin.syncMemories(true);
          new import_obsidian.Notice(`Connection successful! Found memories in your Omi account.`);
        } catch (error) {
          new import_obsidian.Notice(`Connection failed: ${error}`);
        } finally {
          button.setButtonText("Test");
          button.setDisabled(false);
        }
      })
    );
    containerEl.createEl("h2", { text: "Folder Configuration" });
    new import_obsidian.Setting(containerEl).setName("Memories Folder").setDesc("Where to save synced memories (relative to vault root)").addText(
      (text) => text.setPlaceholder("Omi/Memories").setValue(this.plugin.settings.memoriesFolder).onChange(async (value) => {
        this.plugin.settings.memoriesFolder = value || DEFAULT_SETTINGS.memoriesFolder;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Conversations Folder").setDesc("Where to save synced conversations (relative to vault root)").addText(
      (text) => text.setPlaceholder("Omi/Conversations").setValue(this.plugin.settings.conversationsFolder).onChange(async (value) => {
        this.plugin.settings.conversationsFolder = value || DEFAULT_SETTINGS.conversationsFolder;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Action Items Folder").setDesc("Where to save synced action items/tasks (relative to vault root)").addText(
      (text) => text.setPlaceholder("Omi/Action Items").setValue(this.plugin.settings.actionItemsFolder).onChange(async (value) => {
        this.plugin.settings.actionItemsFolder = value || DEFAULT_SETTINGS.actionItemsFolder;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Sync Options" });
    new import_obsidian.Setting(containerEl).setName("Sync on Startup").setDesc("Automatically sync when Obsidian starts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (value) => {
        this.plugin.settings.syncOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto Sync").setDesc("Automatically sync at regular intervals").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
        if (value) {
          this.plugin.startAutoSync();
          new import_obsidian.Notice(`Auto-sync enabled (every ${this.plugin.settings.syncIntervalMinutes} minutes)`);
        } else {
          this.plugin.stopAutoSync();
          new import_obsidian.Notice("Auto-sync disabled");
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync Interval").setDesc("How often to sync (in minutes) when auto-sync is enabled").addSlider(
      (slider) => slider.setLimits(5, 120, 5).setValue(this.plugin.settings.syncIntervalMinutes).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.syncIntervalMinutes = value;
        await this.plugin.saveSettings();
        if (this.plugin.settings.autoSync) {
          this.plugin.startAutoSync();
        }
      })
    );
    containerEl.createEl("h2", { text: "Content Options" });
    new import_obsidian.Setting(containerEl).setName("Include Transcript").setDesc("Include full transcript in memory and conversation notes").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeTranscript).onChange(async (value) => {
        this.plugin.settings.includeTranscript = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Tag Configuration" });
    containerEl.createEl("p", {
      text: "Customize the tags applied to each type of synced item. Use comma-separated values (e.g., 'tag1, tag2, nested/tag').",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Memory Tags").setDesc("Tags to apply to all synced memories").addText(
      (text) => text.setPlaceholder("omi, omi/memory").setValue(this.plugin.settings.memoryTags).onChange(async (value) => {
        this.plugin.settings.memoryTags = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include Category as Tag").setDesc("Automatically add the memory category (e.g., 'meeting', 'personal') as a tag").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeCategoryTag).onChange(async (value) => {
        this.plugin.settings.includeCategoryTag = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Conversation Tags").setDesc("Tags to apply to all synced conversations").addText(
      (text) => text.setPlaceholder("omi, omi/conversation").setValue(this.plugin.settings.conversationTags).onChange(async (value) => {
        this.plugin.settings.conversationTags = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Action Item Tags").setDesc("Base tags to apply to all synced action items").addText(
      (text) => text.setPlaceholder("omi, omi/action-item").setValue(this.plugin.settings.actionItemTags).onChange(async (value) => {
        this.plugin.settings.actionItemTags = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Completed Action Item Tags").setDesc("Additional tags to apply when an action item is completed").addText(
      (text) => text.setPlaceholder("completed, done").setValue(this.plugin.settings.actionItemCompletedTags).onChange(async (value) => {
        this.plugin.settings.actionItemCompletedTags = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Pending Action Item Tags").setDesc("Additional tags to apply when an action item is not yet completed").addText(
      (text) => text.setPlaceholder("todo, pending").setValue(this.plugin.settings.actionItemPendingTags).onChange(async (value) => {
        this.plugin.settings.actionItemPendingTags = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Manual Sync" });
    new import_obsidian.Setting(containerEl).setName("Sync Now").setDesc("Manually trigger a full sync of all Omi data").addButton(
      (button) => button.setButtonText("Sync All").setCta().onClick(async () => {
        await this.plugin.syncAll();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync Memories Only").addButton(
      (button) => button.setButtonText("Sync Memories").onClick(async () => {
        await this.plugin.syncMemories();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync Conversations Only").addButton(
      (button) => button.setButtonText("Sync Conversations").onClick(async () => {
        await this.plugin.syncConversations();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync Action Items Only").addButton(
      (button) => button.setButtonText("Sync Action Items").onClick(async () => {
        await this.plugin.syncActionItems();
      })
    );
    if (this.plugin.settings.lastSyncTimestamp > 0) {
      const lastSync = new Date(this.plugin.settings.lastSyncTimestamp);
      containerEl.createEl("p", {
        text: `Last sync: ${lastSync.toLocaleString()}`,
        cls: "setting-item-description"
      });
    }
    containerEl.createEl("h2", { text: "Help" });
    containerEl.createEl("p", {
      text: "To get your API key:"
    });
    const helpList = containerEl.createEl("ol");
    helpList.createEl("li", { text: "Open the Omi app on your phone" });
    helpList.createEl("li", { text: "Go to Settings \u2192 Developer" });
    helpList.createEl("li", { text: "Tap 'Create Key'" });
    helpList.createEl("li", { text: "Copy the key immediately (you won't see it again!)" });
    helpList.createEl("li", { text: "Paste it in the API Key field above" });
    containerEl.createEl("p", {
      text: "For more information, visit the Omi documentation at docs.omi.me"
    });
  }
};
